CaosNews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('periodistas', PeriodistaViewSet)
router.register('noticias', NoticiaViewSet)
router.register('categorias', CategoriaViewSet)

urlpatterns = [
    path('', index, name="index"),
    path('categoria/', categoria, name="categoria"),
    path('contacto/', contacto, name="contacto"),
    path('register/', register, name="register"),
    path('cuenta_lock/', cuenta_lock, name="cuenta_lock"),

    path('periodistas/', periodistas, name="periodistas"),
    path('periodistas/add/', periodistasadd, name="periodistasadd"),
    path('periodistas/update/<id>/', periodistasupdate, name="periodistasupdate"),
    path('periodistas/delete/<id>/', periodistasdelete, name="periodistasdelete"),
    path('perfilPerio/<id>/', perfilPerio, name="perfilPerio"),
    
    path('single/<id>/', single, name="single"),
    path('noticias/', noticias, name="noticias"),
    path('noticias/add/', noticiasadd, name="noticiasadd"),
    path('noticias/update/<id>/', noticiasupdate, name="noticiasupdate"),
    path('noticias/delete/<id>/', noticiasdelete, name="noticiasdelete"),
    path('servicios/', servicios, name="servicios"),

    # API
    path('api/', include(router.urls)),
    path('noticiasapi/', noticiasapi, name="noticiasapi"),
    path('noticiadetalle/<id>/', noticiadetalle, name="noticiadetalle"),
    path('climaapi/', climaapi, name="climaapi"),

    # Baucher
    path('voucher/', voucher, name="voucher"),

    # Password reset
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html"), name="password_reset"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_complete"),
]

core/models.py
from django.db import models

class Categoria(models.Model):
    descripcion = models.CharField(max_length=20)

    def __str__(self):
        return self.descripcion

class Periodista(models.Model):
    rut = models.CharField(max_length=12)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    edad = models.IntegerField(default=0)
    telefono = models.CharField(max_length=20)
    correo = models.CharField(max_length=50)
    genero = models.CharField(max_length=20)
    imagen_perfil = models.ImageField(upload_to='noticias', blank=True, null=True)

    def __str__(self):
        return self.nombre

class Noticia(models.Model):
    titulo = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    periodista = models.ForeignKey(Periodista, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    habilitado = models.BooleanField(default=True)
    imagen = models.ImageField(upload_to='noticia', blank=True, null=True)

    def __str__(self):
        return self.titulo

class Pago(models.Model):
    nombre_usuario = models.CharField(max_length=100)
    email_usuario = models.EmailField()
    fecha = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Pago {self.transaction_id} de {self.customer_name}"

core/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from captcha.fields import CaptchaField


class PeriodistaForm(ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Periodista
        fields = '__all__'  

class NoticiasForm(ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Noticia
        fields = '__all__'

class UserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']

core/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from random import choice
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required,permission_required
from rest_framework import viewsets
from .serializers import *
from rest_framework.renderers import JSONRenderer
import requests
from django.core.paginator import Paginator

#API metodos de listar
def noticiasapi(request):
    try:
        # Obtener noticias desde tu propia API (ejemplo)
        response_noticias = requests.get('https://caosnews.vercel.app/api/noticias/')
        response_noticias.raise_for_status()  # Lanza excepción para errores HTTP
        noticias = response_noticias.json()

        ciudad = 'Santiago'  # Puedes cambiar la ciudad a la que desees
        url = f'https://wttr.in/{ciudad}?format=j1'
        response_clima = requests.get(url)

        # Obtener valores desde la API de Mindicador
        response_mindicador = requests.get('https://www.mindicador.cl/api')
        response_mindicador.raise_for_status()  # Lanza una excepción para errores HTTP
        valores = response_mindicador.json()

        uf = valores['uf']['valor']  # Valor de la UF
        dolar = valores['dolar']['valor']  # Valor del dólar
        euro = valores['euro']['valor']  # Valor del euro

        aux = {
            'lista': noticias,
            'uf': uf,
            'dolar': dolar,
            'euro': euro,
        }

        if response_clima.status_code == 200:
            datos_clima = response_clima.json()
            clima = {
                'ciudad': ciudad,
                'temperatura': datos_clima['current_condition'][0]['temp_C'],
                'descripcion': datos_clima['current_condition'][0]['weatherDesc'][0]['value'],
                'humedad': datos_clima['current_condition'][0]['humidity'],
                'viento': datos_clima['current_condition'][0]['windspeedKmph']
            }
        else:
            clima = None

        aux['clima'] = clima

    except requests.exceptions.RequestException as e:
        # Manejar cualquier error de solicitud
        print(f"Error al obtener datos de la API: {e}")
        aux = {
            'lista': [],
            'uf': None,
            'dolar': None,
            'euro': None,
            'clima': None,
        }

    return render(request, 'core/Noticias/crudapi/index.html', aux)



def noticiadetalle(request,id):
    response=requests.get(f'https://caosnews.vercel.app/api/noticias/{id}/')
    noticias = response.json()
    aux = {
        'noticia' : noticias
    }
    return render(request, 'core/Noticias/crudapi/detalle.html', aux)


def climaapi(request):
    ciudad = 'Santiago'  # Puedes cambiar la ciudad a la que desees
    url = f'https://wttr.in/{ciudad}?format=j1'
    
    response = requests.get(url)
    
    if response.status_code == 200:
        datos_clima = response.json()
        
        clima = {
            'ciudad': ciudad,
            'temperatura': datos_clima['current_condition'][0]['temp_C'],
            'descripcion': datos_clima['current_condition'][0]['weatherDesc'][0]['value'],
            'humedad': datos_clima['current_condition'][0]['humidity'],
            'viento': datos_clima['current_condition'][0]['windspeedKmph']
        }
    else:
        clima = None

    return render(request, 'core/periodistas/crudapi/index.html', {'clima': clima})

#API
#ViewSets para manejar las solicitudes http
class PeriodistaViewSet(viewsets.ModelViewSet):
    queryset = Periodista.objects.all().order_by('id')
    serializer_class = PeriodistaSerializer
    renderer_classes = [JSONRenderer]

class NoticiaViewSet(viewsets.ModelViewSet):
    queryset = Noticia.objects.all().order_by('id')
    serializer_class = NoticiaSerializer
    renderer_classes = [JSONRenderer]

class CategoriaViewSet(viewsets.ModelViewSet):
    queryset = Categoria.objects.all().order_by('id')
    serializer_class = CategoriaSerializer
    renderer_classes = [JSONRenderer]
#ViewSets

# permisos
def user_in_group (user, group_name):
    return user.groups.filter(name=group_name).exists()

def group_required(group_name):
    def decorator(view_func):
        @login_required
        def _wrapped_view(request, *args, **kwargs):
            if user_in_group(request.user, group_name):
                return view_func(request, *args, **kwargs)
            else:
                messages.error(request,"NO TIENES PERMISOS PARA ACCEDER A ESTA PAGINA")
                return redirect(to='index')
        return _wrapped_view
    return decorator

def register (request):
    aux = {
        'form' : UserCreationForm()
    }
    if request.method == 'POST':
        formulario = UserCreationForm(data=request.POST)
        if formulario.is_valid():
            usuario = formulario.save()
            grupos = Group.objects.get(name='periodista')
            usuario.groups.add(grupos)
            messages.success(request, "Usuario agregado correctamente")
            return redirect(to="periodistas")
        else:
            aux['form'] =  formulario

    return render(request, 'registration/register.html', aux)
# permisos


# Cosas generales
def index(request):
    noticias = Noticia.objects.all()
    categoria = Categoria.objects.all()
    noticia_aleatoria = choice(noticias)
    periodistas = Periodista.objects.all()

    aux = {
        'lista': categoria,
        'lista2': noticias,
        'lista3': periodistas,
        'noticia_aleatoria': noticia_aleatoria,
    }
    return render(request, 'core/index.html', aux)

def categoria (request):
    return render(request, 'core/categoria.html')

def contacto (request):
    return render(request, 'core/contacto.html')

def cuenta_lock (request):
    return render(request, 'core/cuenta_b.html')
# Cosas generales




#   periodistas

def periodistas(request):
    periodista_list = Periodista.objects.all()
    paginator = Paginator(periodista_list, 3)  # 3 periodistas por página

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'lista': page_obj,
    }
    return render(request, 'core/periodistas/index.html', context)  

@group_required('supervisor')
def periodistasadd (request):
    aux = {
        'form' : PeriodistaForm()
    }

    if request.method == 'POST' :
        formulario = PeriodistaForm(request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request,'Periodista creado correctamente')
        else:
            aux['form'] = formulario
            messages.error(request,'Error al crear el periodista')

    return render(request, 'core/periodistas/crud/add.html',aux)

@group_required('supervisor')
def periodistasupdate (request,id):
    periodista = Periodista.objects.get(id=id)
    aux = {
        'form' : PeriodistaForm(instance=periodista)
    }

    if request.method == 'POST' :
        formulario = PeriodistaForm(data=request.POST, instance=periodista, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            aux['form'] = formulario
            messages.success(request,'Periodista actualizado correctamente')
        else:
            aux['form'] = formulario
            messages.error(request,'Error al actualizar el empleado')

    return render(request, 'core/periodistas/crud/update.html', aux)

@group_required('supervisor')
@permission_required('core.delete_periodista')
def periodistasdelete (request,id):
    periodista = Periodista.objects.get(id=id)
    periodista.delete()

    return redirect(to="periodistas")

def perfilPerio(request,id):
    periodista = Periodista.objects.get(id=id)
    noticia = Noticia.objects.all()

    aux = {
        'periodista' : periodista,
        'noticia': noticia
    }

    return render(request, 'core/perfilPerio.html', aux)
    
#    fin periodistas




#    NOTICIAS

def single (request,id):
    noticias = Noticia.objects.get(id=id)
    aux = {
        'noticia' : noticias
    }
    return render(request, 'core/single.html',aux)




def noticias(request):
    noticias_list = Noticia.objects.all()
    paginator = Paginator(noticias_list, 3)  # 3 noticias por página

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'lista': page_obj,
    }
    return render(request, 'core/Noticias/noticias.html', context)


@group_required('periodista')
def noticiasadd (request):
    aux = {
        'form' : NoticiasForm()
    }
    
    if request.method == 'POST' :
        formulario = NoticiasForm(request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request,'Noticia agregada correctamente')
        else:
            aux['form'] = formulario
            messages.error(request,'Error al agregada la Noticia')

    return render(request, 'core/Noticias/Crud/addN.html', aux)


@group_required('supervisor')
def noticiasupdate (request,id):
    noticias = Noticia.objects.get(id=id)
    aux = {
        'form' : NoticiasForm(instance=noticias)
    }
    
    if request.method == 'POST' :
        formulario = NoticiasForm(data=request.POST, instance=noticias, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            aux['form'] = formulario
            messages.success(request,'Noticia modificada correctamente')
        else:
            aux['form'] = formulario
            messages.error(request,'Error al modificar la Noticia')

    return render(request, 'core/Noticias/Crud/updateN.html',aux)


@group_required('supervisor')
def noticiasdelete (request,id):
    noticias = Noticia.objects.get(id=id)
    noticias.delete()
    
    return redirect(to="noticias")

#    FIN NOTICIAS

#servicios
def servicios (request):
    return render(request, 'core/servicios.html')

core/templates/core/periodistas/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block menu %}
<a href="{% url 'index' %}" class="nav-item nav-link ">Home</a>
<div class="nav-item dropdown">
    <a href="#" class="nav-link  dropdown-toggle" data-toggle="dropdown">Noticias</a>
    <div class="dropdown-menu ">
        <a href="{% url 'noticias' %}" class="dropdown-item">Listar</a>
    </div>
</div>
<div class="nav-item dropdown">
    <a href="#" class="nav-link active   dropdown-toggle" data-toggle="dropdown">Periodistas</a>
    <div class="dropdown-menu rounded-0 m-0">
        <a href="{% url 'periodistas' %}" class="dropdown-item">Listar</a>
    </div>
</div>
<a href="{% url 'servicios' %}" class="nav-item nav-link">Apóyanos!</a>
</div>
<div class="input-group ml-auto d-none d-lg-flex" style="width: 100%; max-width: 300px;">
    <input type="text" class="form-control border-0" placeholder="Keyword">
    <div class="input-group-append">
        <button class="input-group-text bg-primary text-dark border-0 px-3"><i class="fa fa-search"></i></button>
    </div>
</div>
{% endblock %}
{% block principal %}
<div class="container-fluid mb-1">
    <div class="title my-1" style="justify-content: center;">
        <h4 class="text-uppercase font-weight-bold p-3" style="text-align: center;">Lista Periodistas</h4>
    </div>

    <div class="bg-white border p-3">
        <div class="table-responsive bg-white mb-3">
            <table class="table table-hover table-dark table-bordered">
                 <thead>
                    <tr>
                        <th>Perfil</th>
                        <th>Nombre</th>
                        <th>Correo</th>
                        <th>Noticias Subidas</th>
                        {% if user.is_staff %}
                        <th>Administrar</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for x in lista %}
                    <tr>
                        <td>
                            {% if x.imagen_perfil %}
                            <img class="img-fluid ml-2" src="{{ x.imagen_perfil.url }}" alt="" style="width: 110px; height: 110px;">
                            {% else %}
                            <img class="img-fluid" src="{% static 'core/img/news-110x110-3.jpg'%}" alt="">
                            {% endif %}
                        </td>
                        <td>
                            <div class="justify-content-start">
                                <div class="mb-2">

                                </div>
                                <a class=" text-white text-uppercase font-weight-bold" href="{% url 'perfilPerio' x.id %}">{{ x.nombre }} {{ x.apellido }} </a>
                            </div>
                        </td>
                        <td>
                            <p class="text-white text-uppercase font-weight-bold">{{ x.correo }}</p>
                        </td>
                        <td>
                            {% for y in lista2 %}
                                {% if x.id == y.periodista.id %}
                                <div class="justify-content-start">
                                    <div class="mb-2">
                                        <a class="badge badge-primary text-uppercase font-weight-semi-bold "
                                            href="">{{ y.titulo }}</a>
                                    </div>
                                </div>
                                {% elif x.id  in y %}
                                <div class="justify-content-start">
                                    <div class="mb-2">
                                        <a class="badge badge-primary text-uppercase font-weight-semi-bold "
                                            href="">NO TIENE NOTICIAS SUBIDAS </a>
                                    </div>
                                </div>
                                {% endif  %}
                            {% endfor %}
                        </td>
                        {% if perms.core.change_periodista %}
                        <td>
                            <a class="btn btn-primary flex-fill" href="{% url 'periodistasupdate' x.id %}" style="width: 100px;">Modificar</a>
                            <a class="btn btn-danger flex-fill" onclick="EliminarPeri( {{ x.id }} )" style="width: 100px;">Eliminar</a>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <!-- Paginación -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if lista.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">Primera</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ lista.previous_page_number }}">Anterior</a>
                </li>
                {% endif %}

                <li class="page-item disabled">
                    <a class="page-link" href="#">Página {{ lista.number }} de {{ lista.paginator.num_pages }}</a>
                </li>

                {% if lista.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ lista.next_page_number }}">Siguiente</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ lista.paginator.num_pages }}">Última</a>
                </li>
                {% endif %}
            </ul>
        </nav> 
        

        <!-- Opción para agregar un nuevo periodista (si el usuario tiene permisos) -->
        {% if perms.core.add_periodista %}
        <div class="d-flex">
            <a class="btn btn-success flex-fill" href="{% url 'periodistasadd' %}" style="width: 100%;">Agregar</a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}