CaosNews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('periodistas', PeriodistaViewSet)
router.register('noticias', NoticiaViewSet)
router.register('categorias', CategoriaViewSet)

urlpatterns = [
    path('', index, name="index"),
    path('categoria/', categoria, name="categoria"),
    path('contacto/', contacto, name="contacto"),
    path('register/', register, name="register"),
    path('cuenta_lock/', cuenta_lock, name="cuenta_lock"),

    path('periodistas/', periodistas, name="periodistas"),
    path('periodistas/add/', periodistasadd, name="periodistasadd"),
    path('periodistas/update/<id>/', periodistasupdate, name="periodistasupdate"),
    path('periodistas/delete/<id>/', periodistasdelete, name="periodistasdelete"),
    path('perfilPerio/<id>/', perfilPerio, name="perfilPerio"),
    
    path('single/<id>/', single, name="single"),
    path('noticias/', noticias, name="noticias"),
    path('noticias/add/', noticiasadd, name="noticiasadd"),
    path('noticias/update/<id>/', noticiasupdate, name="noticiasupdate"),
    path('noticias/delete/<id>/', noticiasdelete, name="noticiasdelete"),
    path('servicios/', servicios, name="servicios"),

    # API
    path('api/', include(router.urls)),
    path('noticiasapi/', noticiasapi, name="noticiasapi"),
    path('noticiadetalle/<id>/', noticiadetalle, name="noticiadetalle"),
    path('climaapi/', climaapi, name="climaapi"),

    # Baucher
    path('voucher/', voucher, name="voucher"),

    # Password reset
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html"), name="password_reset"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_complete"),
]

core/models.py
from django.db import models

class Categoria(models.Model):
    descripcion = models.CharField(max_length=20)

    def __str__(self):
        return self.descripcion

class Periodista(models.Model):
    rut = models.CharField(max_length=12)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    edad = models.IntegerField(default=0)
    telefono = models.CharField(max_length=20)
    correo = models.CharField(max_length=50)
    genero = models.CharField(max_length=20)
    imagen_perfil = models.ImageField(upload_to='noticias', blank=True, null=True)

    def __str__(self):
        return self.nombre

class Noticia(models.Model):
    titulo = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    periodista = models.ForeignKey(Periodista, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    habilitado = models.BooleanField(default=True)
    imagen = models.ImageField(upload_to='noticia', blank=True, null=True)

    def __str__(self):
        return self.titulo

class Pago(models.Model):
    nombre_usuario = models.CharField(max_length=100)
    email_usuario = models.EmailField()
    fecha = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Pago {self.transaction_id} de {self.customer_name}"

core/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from captcha.fields import CaptchaField


class PeriodistaForm(ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Periodista
        fields = '__all__'  

class NoticiasForm(ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Noticia
        fields = '__all__'

class UserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']

core/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from random import choice
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required,permission_required
from rest_framework import viewsets
from .serializers import *
from rest_framework.renderers import JSONRenderer
import requests
from django.core.paginator import Paginator

#API metodos de listar
def noticiasapi(request):
    try:
        # Obtener noticias desde tu propia API (ejemplo)
        response_noticias = requests.get('https://caosnews.vercel.app/api/noticias/')
        response_noticias.raise_for_status()  # Lanza excepción para errores HTTP
        noticias = response_noticias.json()

        ciudad = 'Santiago'  # Puedes cambiar la ciudad a la que desees
        url = f'https://wttr.in/{ciudad}?format=j1'
        response_clima = requests.get(url)

        # Obtener valores desde la API de Mindicador
        response_mindicador = requests.get('https://www.mindicador.cl/api')
        response_mindicador.raise_for_status()  # Lanza una excepción para errores HTTP
        valores = response_mindicador.json()

        uf = valores['uf']['valor']  # Valor de la UF
        dolar = valores['dolar']['valor']  # Valor del dólar
        euro = valores['euro']['valor']  # Valor del euro

        aux = {
            'lista': noticias,
            'uf': uf,
            'dolar': dolar,
            'euro': euro,
        }

        if response_clima.status_code == 200:
            datos_clima = response_clima.json()
            clima = {
                'ciudad': ciudad,
                'temperatura': datos_clima['current_condition'][0]['temp_C'],
                'descripcion': datos_clima['current_condition'][0]['weatherDesc'][0]['value'],
                'humedad': datos_clima['current_condition'][0]['humidity'],
                'viento': datos_clima['current_condition'][0]['windspeedKmph']
            }
        else:
            clima = None

        aux['clima'] = clima

    except requests.exceptions.RequestException as e:
        # Manejar cualquier error de solicitud
        print(f"Error al obtener datos de la API: {e}")
        aux = {
            'lista': [],
            'uf': None,
            'dolar': None,
            'euro': None,
            'clima': None,
        }

    return render(request, 'core/Noticias/crudapi/index.html', aux)



def noticiadetalle(request,id):
    response=requests.get(f'https://caosnews.vercel.app/api/noticias/{id}/')
    noticias = response.json()
    aux = {
        'noticia' : noticias
    }
    return render(request, 'core/Noticias/crudapi/detalle.html', aux)


def climaapi(request):
    ciudad = 'Santiago'  # Puedes cambiar la ciudad a la que desees
    url = f'https://wttr.in/{ciudad}?format=j1'
    
    response = requests.get(url)
    
    if response.status_code == 200:
        datos_clima = response.json()
        
        clima = {
            'ciudad': ciudad,
            'temperatura': datos_clima['current_condition'][0]['temp_C'],
            'descripcion': datos_clima['current_condition'][0]['weatherDesc'][0]['value'],
            'humedad': datos_clima['current_condition'][0]['humidity'],
            'viento': datos_clima['current_condition'][0]['windspeedKmph']
        }
    else:
        clima = None

    return render(request, 'core/periodistas/crudapi/index.html', {'clima': clima})

#API
#ViewSets para manejar las solicitudes http
class PeriodistaViewSet(viewsets.ModelViewSet):
    queryset = Periodista.objects.all().order_by('id')
    serializer_class = PeriodistaSerializer
    renderer_classes = [JSONRenderer]

class NoticiaViewSet(viewsets.ModelViewSet):
    queryset = Noticia.objects.all().order_by('id')
    serializer_class = NoticiaSerializer
    renderer_classes = [JSONRenderer]

class CategoriaViewSet(viewsets.ModelViewSet):
    queryset = Categoria.objects.all().order_by('id')
    serializer_class = CategoriaSerializer
    renderer_classes = [JSONRenderer]
#ViewSets

# permisos
def user_in_group (user, group_name):
    return user.groups.filter(name=group_name).exists()

def group_required(group_name):
    def decorator(view_func):
        @login_required
        def _wrapped_view(request, *args, **kwargs):
            if user_in_group(request.user, group_name):
                return view_func(request, *args, **kwargs)
            else:
                messages.error(request,"NO TIENES PERMISOS PARA ACCEDER A ESTA PAGINA")
                return redirect(to='index')
        return _wrapped_view
    return decorator

def register (request):
    aux = {
        'form' : UserCreationForm()
    }
    if request.method == 'POST':
        formulario = UserCreationForm(data=request.POST)
        if formulario.is_valid():
            usuario = formulario.save()
            grupos = Group.objects.get(name='periodista')
            usuario.groups.add(grupos)
            messages.success(request, "Usuario agregado correctamente")
            return redirect(to="periodistas")
        else:
            aux['form'] =  formulario

    return render(request, 'registration/register.html', aux)
# permisos


# Cosas generales
def index(request):
    noticias = Noticia.objects.all()
    categoria = Categoria.objects.all()
    noticia_aleatoria = choice(noticias)
    periodistas = Periodista.objects.all()

    aux = {
        'lista': categoria,
        'lista2': noticias,
        'lista3': periodistas,
        'noticia_aleatoria': noticia_aleatoria,
    }
    return render(request, 'core/index.html', aux)

def categoria (request):
    return render(request, 'core/categoria.html')

def contacto (request):
    return render(request, 'core/contacto.html')

def cuenta_lock (request):
    return render(request, 'core/cuenta_b.html')
# Cosas generales




#   periodistas

def periodistas(request):
    periodista_list = Periodista.objects.all()
    paginator = Paginator(periodista_list, 3)  # 3 periodistas por página

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'lista': page_obj,
    }
    return render(request, 'core/periodistas/index.html', context)  

@group_required('supervisor')
def periodistasadd (request):
    aux = {
        'form' : PeriodistaForm()
    }

    if request.method == 'POST' :
        formulario = PeriodistaForm(request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request,'Periodista creado correctamente')
        else:
            aux['form'] = formulario
            messages.error(request,'Error al crear el periodista')

    return render(request, 'core/periodistas/crud/add.html',aux)

@group_required('supervisor')
def periodistasupdate (request,id):
    periodista = Periodista.objects.get(id=id)
    aux = {
        'form' : PeriodistaForm(instance=periodista)
    }

    if request.method == 'POST' :
        formulario = PeriodistaForm(data=request.POST, instance=periodista, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            aux['form'] = formulario
            messages.success(request,'Periodista actualizado correctamente')
        else:
            aux['form'] = formulario
            messages.error(request,'Error al actualizar el empleado')

    return render(request, 'core/periodistas/crud/update.html', aux)

@group_required('supervisor')
@permission_required('core.delete_periodista')
def periodistasdelete (request,id):
    periodista = Periodista.objects.get(id=id)
    periodista.delete()

    return redirect(to="periodistas")

def perfilPerio(request,id):
    periodista = Periodista.objects.get(id=id)
    noticia = Noticia.objects.all()

    aux = {
        'periodista' : periodista,
        'noticia': noticia
    }

    return render(request, 'core/perfilPerio.html', aux)
    
#    fin periodistas




#    NOTICIAS

def single (request,id):
    noticias = Noticia.objects.get(id=id)
    aux = {
        'noticia' : noticias
    }
    return render(request, 'core/single.html',aux)




def noticias(request):
    noticias_list = Noticia.objects.all()
    paginator = Paginator(noticias_list, 3)  # 3 noticias por página

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'lista': page_obj,
    }
    return render(request, 'core/Noticias/noticias.html', context)


@group_required('periodista')
def noticiasadd (request):
    aux = {
        'form' : NoticiasForm()
    }
    
    if request.method == 'POST' :
        formulario = NoticiasForm(request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request,'Noticia agregada correctamente')
        else:
            aux['form'] = formulario
            messages.error(request,'Error al agregada la Noticia')

    return render(request, 'core/Noticias/Crud/addN.html', aux)


@group_required('supervisor')
def noticiasupdate (request,id):
    noticias = Noticia.objects.get(id=id)
    aux = {
        'form' : NoticiasForm(instance=noticias)
    }
    
    if request.method == 'POST' :
        formulario = NoticiasForm(data=request.POST, instance=noticias, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            aux['form'] = formulario
            messages.success(request,'Noticia modificada correctamente')
        else:
            aux['form'] = formulario
            messages.error(request,'Error al modificar la Noticia')

    return render(request, 'core/Noticias/Crud/updateN.html',aux)


@group_required('supervisor')
def noticiasdelete (request,id):
    noticias = Noticia.objects.get(id=id)
    noticias.delete()
    
    return redirect(to="noticias")

#    FIN NOTICIAS

#servicios
def servicios (request):
    return render(request, 'core/servicios.html')

core/templates/core/contacto.html
{% extends 'core/base.html' %}
{% load static %}
{% block menu %}
<a href="{% url 'index' %}" class="nav-item nav-link">Home</a>
<div class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Noticias</a>
    <div class="dropdown-menu rounded-0 m-0">
        <a href="{% url 'noticias' %}" class="dropdown-item">Listar</a>
    </div>
</div>
<div class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Periodistas</a>
    <div class="dropdown-menu rounded-0 m-0">
        <a href="{% url 'periodistas' %}" class="dropdown-item">Listar</a>
    </div>
</div>
<a href="{% url 'servicios' %}" class="nav-item nav-link ">Apoyanos!</a>
</div>
<div class="input-group ml-auto d-none d-lg-flex" style="width: 100%; max-width: 300px;">
    <input type="text" class="form-control border-0" placeholder="Keyword">
    <div class="input-group-append">
        <button class="input-group-text bg-primary text-dark border-0 px-3"><i class="fa fa-search"></i></button>
    </div>
</div>
{% endblock %}
{% block principal %}
    <!-- Contact Start -->
    <div class="container-fluid mt-5 pt-3">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Contactanos para cualquier pregunta</h4>
                    </div>
                    <div class="bg-white border border-top-0 p-4 mb-3">
                        <div class="mb-4">
                            <h6 class="text-uppercase font-weight-bold">Informacion de contacto</h6>
							<div class="mb-3">
                                <div class="d-flex align-items-center mb-2">
                                    <i class="fa fa-map-marker-alt text-primary mr-2"></i>
                                    <h6 class="font-weight-bold mb-0">Nuestra oficina</h6>
                                </div>
                                <p class="m-0">123 Street, New York, USA</p>
                            </div>
                            <div class="mb-3">
                                <div class="d-flex align-items-center mb-2">
                                    <i class="fa fa-envelope-open text-primary mr-2"></i>
                                    <h6 class="font-weight-bold mb-0">Mandanos un correo</h6>
                                </div>
                                <p class="m-0">CaosTheme@Peri.com</p>
                            </div>
                            <div class="mb-3">
                                <div class="d-flex align-items-center mb-2">
                                    <i class="fa fa-phone-alt text-primary mr-2"></i>
                                    <h6 class="font-weight-bold mb-0">Llamanos</h6>
                                </div>
                                <p class="m-0">+012 345 6789</p>
                            </div>
                        </div>
                        <h6 class="text-uppercase font-weight-bold mb-3">Contactanos</h6>
                        <form>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="text" class="form-control p-4" placeholder="Tu nombre" required="required"/>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="email" class="form-control p-4" placeholder="Tu email" required="required"/>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control p-4" placeholder="Razon" required="required"/>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" rows="4" placeholder="Mensaje" required="required"></textarea>
                            </div>
                            <div>
                                <button class="btn btn-primary font-weight-semi-bold px-4" style="height: 50px;"
                                    type="submit">Enviar Mensaje</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <!-- Social Follow Start -->
                    <div class="mb-3">
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Siguenos</h4>
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #39569E;">
                                <i class="fab fa-facebook-f text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Fans</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #52AAF4;">
                                <i class="fab fa-twitter text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Followers</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #0185AE;">
                                <i class="fab fa-linkedin-in text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Connects</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #C8359D;">
                                <i class="fab fa-instagram text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Followers</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #DC472E;">
                                <i class="fab fa-youtube text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Subscribers</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none" style="background: #055570;">
                                <i class="fab fa-vimeo-v text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Followers</span>
                            </a>
                        </div>
                    </div>
                    <!-- Social Follow End -->
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->
{% endblock %}

core/templates/core/cuenta_b.html
{% extends 'core/base.html' %}
{% load static %}
{% block menu %}
<a href="{% url 'index' %}" class="nav-item nav-link">Home</a>
<a href="{% url 'categoria' %}" class="nav-item nav-link">Category</a>
<div class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Noticias</a>
    <div class="dropdown-menu rounded-0 m-0">
        <a href="{% url 'noticias' %}" class="dropdown-item">Listar</a>
    </div>
</div>
<div class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Periodistas</a>
    <div class="dropdown-menu rounded-0 m-0">
        <a href="{% url 'periodistas' %}" class="dropdown-item">Listar</a>
    </div>
</div>
</div>
<div class="input-group ml-auto d-none d-lg-flex" style="width: 100%; max-width: 300px;">
    <input type="text" class="form-control border-0" placeholder="Keyword">
    <div class="input-group-append">
        <button class="input-group-text bg-primary text-dark border-0 px-3"><i class="fa fa-search"></i></button>
    </div>
</div>
{% endblock %}
{% block principal %} 
<div class="container-fluid rounded mt-5" style="margin-left: 10%;">
    <div class="row my-3 bg-dark float-mid" style="margin-right: 3px; width: 80%;">
        <div class="col-sm border rounded p-3 my-2 mx-2" style="height: auto; ">
            <h2 class="text-white">Tu cuenta a sido bloqueada por muchos intentos fallidos, se desbloqueara en 3 minutos </h2>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/perfilPerio.html
{% extends 'core/base.html' %}
{% load static %}
{% block menu %}
<a href="{% url 'index' %}" class="nav-item nav-link ">Home</a>
<div class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Noticias</a>
    <div class="dropdown-menu rounded-0 m-0">
        <a href="{% url 'noticias' %}" class="dropdown-item">Listar</a>
    </div>
</div>
<div class="nav-item dropdown">
    <a href="#" class="nav-link active dropdown-toggle" data-toggle="dropdown">Periodistas</a>
    <div class="dropdown-menu rounded-0 m-0">
        <a href="{% url 'periodistas' %}" class="dropdown-item">Listar</a>
    </div>
</div>
<a href="{% url 'servicios' %}" class="nav-item nav-link ">Apoyanos!</a>
</div>
<div class="input-group ml-auto d-none d-lg-flex" style="width: 100%; max-width: 300px;">
    <input type="text" class="form-control border-0" placeholder="Keyword">
    <div class="input-group-append">
        <button class="input-group-text bg-primary text-dark border-0 px-3"><i class="fa fa-search"></i></button>
    </div>
</div>
{% endblock %}
{% block principal %}
<!-- News With Sidebar Start -->
<div class="container-fluid mt-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <!-- News Detail Start -->
                <div class="position-relative mb-3">
                    <div class="bg-white border border-top-0 p-4">
                        <div class="d-flex align-items-center mb-4">
                            <!-- Colocamos la imagen del periodista -->
                            {% if periodista.imagen_perfil %}
                            <img class="rounded-circle mr-3" src="{{ periodista.imagen_perfil.url }}" width="100" height="100" alt="">
                            {% else %}
                            <img class="rounded-circle mr-3" src="{% static 'core/img/user.jpg' %}" width="100" height="100" alt="">
                            {% endif %}
                            <!-- Colocamos el nombre del periodista -->
                            <div>
                                <h4 class="mb-1 text-uppercase">{{ periodista.nombre }} {{ periodista.apellido }}</h4>
                            </div>
                        </div>
                        
                        <div class="d-flex justify-content-center align-items-center">
                            <a class="badge badge-primary text-uppercase font-weight-semi-bold p-2 mr-2 mt-2" href="">Edad: {{ periodista.edad }}</a>
                            <a class="badge badge-primary text-uppercase font-weight-semi-bold p-2 mr-2 mt-2" href="">Correo: {{ periodista.correo }}</a>
                            <a class="badge badge-primary text-uppercase font-weight-semi-bold p-2 mr-2 mt-2" href="">Teléfono: {{ periodista.telefono }}</a>
                        </div>      
                        <div class="mt-3">
                            <h4>Noticias creadas por: <p class="text-uppercase mt-2">{{ periodista.nombre }} {{ periodista.apellido }}</p></h4>
                            <ul class="list-unstyled">
                                {% for n in periodista.noticia_set.all %}
                                <li class="media mb-3">
                                    <img class="mr-3 rounded" src="{{ n.imagen.url }}" width="100" height="100" alt="">
                                    <div class="media-body">
                                        <h5 class="mt-0 mb-1"><a href="{% url 'single' n.id %}" class="text-dark">{{ n.titulo }}</a></h5>
                                        <p class="badge badge-primary text-uppercase font-weight-semi-bold p-2 mr-2 mt-2">{{ n.categoria }}</p>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                            
                        </div>                  
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <!-- Social Follow Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Follow Us</h4>
                    </div>
                    <div class="bg-white border border-top-0 p-3">
                        <a href="{% url 'contacto' %}" class="d-block w-100 text-white text-decoration-none mb-3"
                            style="background: #39569E;">
                            <i class="fab fa-facebook-f text-center py-4 mr-3"
                                style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Fans</span>
                        </a>
                        <a href="{% url 'contacto' %}" class="d-block w-100 text-white text-decoration-none mb-3"
                            style="background: #52AAF4;">
                            <i class="fab fa-twitter text-center py-4 mr-3"
                                style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Followers</span>
                        </a>
                        <a href="{% url 'contacto' %}" class="d-block w-100 text-white text-decoration-none mb-3"
                            style="background: #0185AE;">
                            <i class="fab fa-linkedin-in text-center py-4 mr-3"
                                style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Connects</span>
                        </a>
                        <a href="{% url 'contacto' %}" class="d-block w-100 text-white text-decoration-none mb-3"
                            style="background: #C8359D;">
                            <i class="fab fa-instagram text-center py-4 mr-3"
                                style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Followers</span>
                        </a>
                        <a href="{% url 'contacto' %}" class="d-block w-100 text-white text-decoration-none mb-3"
                            style="background: #DC472E;">
                            <i class="fab fa-youtube text-center py-4 mr-3"
                                style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Subscribers</span>
                        </a>
                        <a href="{% url 'contacto' %}" class="d-block w-100 text-white text-decoration-none"
                            style="background: #055570;">
                            <i class="fab fa-vimeo-v text-center py-4 mr-3"
                                style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Followers</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}